dist: bionic
language: python

notifications:
  email: false

python:
- "3.6"
- "3.7"
- "3.8"

before_install:
- sudo apt-get install -y libgdal-dev
- sudo apt-get install graphviz
- sudo apt-get install proj-bin
- sudo apt-get install gcc
- sudo apt-get install libproj-dev

install:
- pip install -r requirements-dev.txt --upgrade
- if [ $TRAVIS_PYTHON_VERSION == '3.6' ]; then
    python install_all.py -e;
  else
    python install_all.py;
  fi

script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sentinelhub.config --instance_id $INSTANCE_ID &&
    sentinelhub.config --sh_client_secret $SH_CLIENT_SECRET &&
    sentinelhub.config --sh_client_id $SH_CLIENT_ID ;
  fi
- if [ $TRAVIS_PYTHON_VERSION == '3.6' ]; then
    pylint core/eolearn/core/*.py &&
    pylint coregistration/eolearn/coregistration/*.py &&
    pylint features/eolearn/features/*.py &&
    pylint geometry/eolearn/geometry/*.py &&
    pylint io/eolearn/io/*.py &&
    pylint mask/eolearn/mask/*.py &&
    pylint ml_tools/eolearn/ml_tools/*.py &&
    pylint visualization/eolearn/visualization/*.py;
  fi
- >
  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    if [ $TRAVIS_PYTHON_VERSION == '3.6' ]; then
      pytest -c=.coveragerc;
    else
      pytest;
    fi;
  else
    pytest \
      --ignore io/eolearn/tests/test_sentinelhub_process.py ;
  fi
# - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then pytest --nbval-lax examples/visualization/EOPatchVisualization.ipynb  ; fi'

after_success:
- if [ $TRAVIS_PYTHON_VERSION == '3.6' ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then codecov; fi
